/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Domain.Appointment;
import Domain.Type;
import control.PatientControl;
import java.awt.Color;

/**
 *
 * @author orlandocamacho
 */
public class AppointmentSRP extends javax.swing.JPanel {

    Color surgicalN = new Color(253,39,107);
    Color surgicalR = new Color(254,78,137);
    
    /**
     * Creates new form AppointmentRP
     */
    public AppointmentSRP(Appointment appointment) {
        initComponents();
        renderAppointmentRP(appointment);
    }
    
    public void renderAppointmentRP(Appointment appointment){
        jLabel1.setText("Px: " + PatientControl.getInstance().getPatientsByID(appointment.getPatient()));
        
        if (appointment.getType() == Type.New) {
            jLabel2.setText("N");
            if (appointment.isConfirmation()) {
                rPBorder.setBackground(surgicalN);
                roundedApp1.setBackground(surgicalN);
            } else {
                rPBorder.setBackground(surgicalN);
                roundedApp1.setBackground(Color.white);
            }
        } else {
            jLabel2.setText("R");
            if (appointment.isConfirmation()) {
                rPBorder.setBackground(surgicalR);
                roundedApp1.setBackground(surgicalR);
            } else {
                rPBorder.setBackground(surgicalR);
                roundedApp1.setBackground(Color.white);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rPBorder = new Components.RoundedPanel();
        roundedApp1 = new Components.RoundedApp();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rPBorder.setBackground(new java.awt.Color(0, 153, 51));
        rPBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedApp1.setBackground(new java.awt.Color(255, 255, 255));
        roundedApp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 36, 37));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Px: Orlando Camacho Gámez");
        roundedApp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 110, 25));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 36, 37));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S");
        jLabel2.setToolTipText("");
        roundedApp1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 0, 11, 26));

        rPBorder.add(roundedApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 136, 122));

        add(rPBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 126));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Components.RoundedPanel rPBorder;
    private Components.RoundedApp roundedApp1;
    // End of variables declaration//GEN-END:variables
}
