/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Domain.Appointment;
import Domain.AppointmentType;
import Domain.Type;
import SIM.App;
import View.AppointmentInfo;
import control.PatientControl;
import java.awt.Color;

/**
 *
 * @author orlandocamacho
 */
public class AppointmentNERP extends javax.swing.JPanel {

    Color nutritionalN = new Color(11,134,81);
    Color nutritionalR = new Color(79,195,97);
    Color estheticN = new Color(254,182,0);
    Color estheticR = new Color(251,225,97);
    
    /**
     * Creates new form AppointmentRP
     */
    public AppointmentNERP(Appointment appointment) {
        initComponents();
        renderAppointmentRP(appointment);
    }
    
    public void renderAppointmentRP(Appointment appointment){
        jLabel1.setText("Px: " + PatientControl.getInstance().getPatientsByID(appointment.getPatient()));
        
        if (appointment.getType() == Type.New) {
            jLabel2.setText("N");
            if (appointment.isConfirmation()) {
                if (appointment.getaType() == AppointmentType.Nutritional) {
                    rPBorder.setBackground(nutritionalN);
                    roundedApp1.setBackground(nutritionalN);
                } else {
                    rPBorder.setBackground(estheticN);
                    roundedApp1.setBackground(estheticN); 
                }
            } else {
                if (appointment.getaType() == AppointmentType.Nutritional) {
                    rPBorder.setBackground(nutritionalN);
                    roundedApp1.setBackground(Color.white);
                } else {
                    rPBorder.setBackground(estheticN);
                    roundedApp1.setBackground(Color.white); 
                }
            }
        } else {
            jLabel2.setText("R");
            if (appointment.isConfirmation()) {
                if (appointment.getaType() == AppointmentType.Nutritional) {
                    rPBorder.setBackground(nutritionalR);
                    roundedApp1.setBackground(nutritionalR);
                } else {
                    rPBorder.setBackground(estheticR);
                    roundedApp1.setBackground(estheticR); 
                }
            } else {
                if (appointment.getaType() == AppointmentType.Nutritional) {
                    rPBorder.setBackground(nutritionalR);
                    roundedApp1.setBackground(Color.white);
                } else {
                    rPBorder.setBackground(estheticR);
                    roundedApp1.setBackground(Color.white); 
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rPBorder = new Components.RoundedPanel();
        roundedApp1 = new Components.RoundedApp();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rPBorder.setBackground(new java.awt.Color(0, 153, 51));
        rPBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedApp1.setBackground(new java.awt.Color(255, 255, 255));
        roundedApp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 36, 37));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S");
        jLabel2.setToolTipText("");
        roundedApp1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 0, 11, 26));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 36, 37));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Px: Orlando Camacho Gámez");
        roundedApp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 110, 25));

        rPBorder.add(roundedApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 136, 26));

        add(rPBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        new AppointmentInfo(App.GetSingleton().getMainFrame(), true);
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Components.RoundedPanel rPBorder;
    private Components.RoundedApp roundedApp1;
    // End of variables declaration//GEN-END:variables
}
