/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Domain.Medicine;

/**
 *
 * @author orlandocamacho
 */
public class MedicineInfo extends javax.swing.JPanel {

    /**
     * Creates new form MedicineInfo
     */
    public MedicineInfo(Medicine medicine) {
        initComponents();
        renderMedicineInfo(medicine);
    }
    
    private void renderMedicineInfo(Medicine medicine){
    
        jLabel4.setText(medicine.getName());
        
        if (medicine.getIngredient() != null) {
            jLabel5.setText(medicine.getIngredient());
        }
        
        jLabel10.setText(medicine.getAmount() + "pz");
        jLabel9.setText(medicine.getMgIngredient() + "mg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel4 = new Components.RoundedPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel4.setBackground(new java.awt.Color(53, 152, 219));
        roundedPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombrej medicamento");
        roundedPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 20));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrediente activo");
        roundedPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("10 mg");
        roundedPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 80, 60, 20));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("10 pz");
        roundedPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 60, 20));

        add(roundedPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 233, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private Components.RoundedPanel roundedPanel4;
    // End of variables declaration//GEN-END:variables
}
