/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Domain.Appointment;
import Domain.Patient;
import View.EditPatient;
import View.RegisterPatient;
import control.AppointmentControl;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author orlandocamacho
 */
public class PatientInfo extends javax.swing.JPanel {

    private EditPatient parent1 = null;
    private RegisterPatient parent2 = null;
    private Patient patient;
    
    /**
     * Creates new form PatientInfo
     */
    public PatientInfo(EditPatient parent, Patient patient) {
        this.parent1 = parent;
        this.patient = patient;
        initComponents();
        renderPatientInfo(patient);
    }
    
    public PatientInfo(RegisterPatient parent, Patient patient) {
        this.parent2 = parent;
        this.patient = patient;
        initComponents();
        renderPatientInfo(patient);
    }
    
    private void renderPatientInfo(Patient patient){
        jLabel4.setText(patient.getName());
        jLabel1.setText(patient.getPhone());
        
        roundedIndicator1.setBackground(new Color(79,195,97));
                
        List<Appointment> appointments = AppointmentControl.getInstance().getAppointmentFromNowOn();
        if (appointments != null) {
            for (Appointment appointment : appointments) {
                
                if (appointment.getPatient().getID() == patient.getID() && !appointment.isConfirmation()) {
                    roundedIndicator1.setBackground(new Color(253, 84, 83));
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel2 = new Components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roundedIndicator1 = new Components.RoundedIndicator();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel2.setBackground(new java.awt.Color(244, 243, 243));
        roundedPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 36, 37));
        jLabel1.setText("631 299 6045");
        roundedPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 36, 37));
        jLabel4.setText("Orlando Camacho Gámez");
        roundedPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        roundedIndicator1.setBackground(new java.awt.Color(79, 195, 97));
        roundedPanel2.add(roundedIndicator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (parent1 != null) {
            parent1.chargePatientInfo(patient);
            parent1.renderAppointmensConf(patient);
        } else {
            parent2.chargePatientInfo(patient);
            parent2.renderAppointmensConf(patient);
        }
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private Components.RoundedIndicator roundedIndicator1;
    private Components.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
