/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Domain.Appointment;
import Domain.Patient;
import com.raven.datechooser.SelectedDate;
import control.AppointmentControl;
import control.PatientControl;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author orlandocamacho
 */
public class ManageAppointments extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleAppointment
     */
    public ManageAppointments() {
        initComponents();
        this.loadPatients();
    }

    private void loadPatients() {
//        for (Patient patient : PatientControl.getInstance().getPatients()) {
//            cbPatient.addItem(patient);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date = new com.raven.datechooser.DateChooser();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1080, 685));
        setPreferredSize(new java.awt.Dimension(1080, 685));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 36, 37));
        jLabel2.setText("Agenda semanal");
        title.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jButton1.setText("Seleccionar fecha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SelectedDate d = date.getSelectedDate();
        //Obtiene la fecha seleccionada del calendario
        Date date1 = new Date(d.getYear() - 1900, d.getMonth(), d.getDay());

        for (Appointment appointment : AppointmentControl.getInstance().getAppointment()) {
            //Obtiene formato de fecha Date de la cita
            Date ddd = new Date(appointment.getStartTime().getTime());
            Calendar calendar = Calendar.getInstance();

            calendar.setTime(ddd);
            int dateYear = calendar.get(Calendar.YEAR);
            int dateMonth = (calendar.get(Calendar.MONTH) + 1);
            int dateDay = calendar.get(Calendar.DAY_OF_MONTH);
            
            
            if (d.getDay() == dateDay && d.getMonth() == dateMonth && d.getYear() == dateYear) {
                
                System.out.println("Cita encontrada en el mismo dia que el que se seleccionó (" + d.getDay() + "-" + d.getMonth() + "-" + d.getYear() + ")\nId appointment: " + appointment.getId_appointment() + "\n\n");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
