/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Components.CustomScrollBarUI;
import Components.MedicineInfo;
import Domain.Medicine;
import SIM.App;
import SIM.MessageType;
import control.MedicineControl;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author orlandocamacho
 */
public class RegisterMedicine extends javax.swing.JPanel {

    /**
     * Creates new form RegisterMedicine
     */
    public RegisterMedicine() {
        initComponents();
        
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        scrollMedicines.setSize(780, 575);
        scrollMedicines.setPreferredSize(new java.awt.Dimension(780, 575));
        revalidate();
        
        renderMedicines();
        
        
    }
    
    private void renderMedicines(){
        scrollMedicines.removeAll();
        
        List<Medicine> medicines = MedicineControl.getInstance().getMedicines();
        
        if (medicines != null) {
            if (medicines.size() > 12) {
                int rows = (int) Math.ceil(medicines.size() / 3.0);
                scrollMedicines.setSize(575, (130 * rows) + 20);
                scrollMedicines.setPreferredSize(new java.awt.Dimension(575, (130 * rows) + 20));
                revalidate();
            }
        }
        
        if (medicines != null) {
            int medC = 1;
            int coorY = 20;
            int coorX = 20;
            for (Medicine medicine : medicines) {
                MedicineInfo medicineInfo = new MedicineInfo(medicine);
                scrollMedicines.add(medicineInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(coorX, coorY, -1, -1));
                coorX += 253;
                if (medC%3 == 0) {
                    coorY += 130;
                    coorX = 20;
                }
                medC += 1;
                
            }
        }
        revalidate();
    }
    
    private boolean validateFields() {
        if (!jTextField1.getText().isBlank() || !jTextField1.getText().isEmpty()) {
            if (jTextField1.getText().length() > 100) {
                return false;
            }
        } else {
            return false;
        }

        if (!jTextField2.getText().isBlank() || !jTextField2.getText().isEmpty()) {
            try {
                Integer.valueOf(jTextField2.getText());
            } catch (NumberFormatException e) {
                return false;
            }
        } else {
            return false;
        }

        if (!jTextField4.getText().isBlank() || !jTextField4.getText().isEmpty()) {
            if (jTextField4.getText().length() > 80) {
                return false;
            }
        }

        if (!jTextField3.getText().isBlank() || !jTextField3.getText().isEmpty()) {
            try {
                Integer.valueOf(jTextField3.getText());
            } catch (NumberFormatException e) {
                return false;
            }
        } else {
            return false;
        }

        if (!tAReason.getText().trim().isBlank() || !tAReason.getText().trim().isEmpty()) {
            if (tAReason.getText().trim().length() > 200) {
                return false;
            }
        }

        return true;
    }

    private void cleanFields() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        tAReason.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLPatient = new javax.swing.JLabel();
        containerBtnSchedule = new Components.RoundedPanel();
        btnSchedule = new javax.swing.JButton();
        containerPatient = new Components.RoundedPanel();
        jTextField1 = new javax.swing.JTextField();
        jLDate = new javax.swing.JLabel();
        containerDay = new Components.RoundedPanel();
        jTextField2 = new javax.swing.JTextField();
        jLBeginning = new javax.swing.JLabel();
        containerEnding = new Components.RoundedPanel();
        jTextField3 = new javax.swing.JTextField();
        jLDate1 = new javax.swing.JLabel();
        containerReason = new Components.RoundedPanel();
        tAReason = new javax.swing.JTextArea();
        jLNotes = new javax.swing.JLabel();
        containerEnding1 = new Components.RoundedPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLDay3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollMedicines = new javax.swing.JPanel();
        roundedPanel3 = new Components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundedPanel4 = new Components.RoundedPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        roundedPanel5 = new Components.RoundedPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roundedPanel6 = new Components.RoundedPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        roundedPanel7 = new Components.RoundedPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        roundedPanel8 = new Components.RoundedPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 685));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 36, 37));
        jLabel2.setText("Registrar medicina");
        title.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLPatient.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLPatient.setForeground(new java.awt.Color(35, 36, 37));
        jLPatient.setText("Nombre:");
        jPanel2.add(jLPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 10));

        containerBtnSchedule.setBackground(new java.awt.Color(37, 119, 241));
        containerBtnSchedule.setLayout(new java.awt.BorderLayout());

        btnSchedule.setBackground(new java.awt.Color(37, 119, 241));
        btnSchedule.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnSchedule.setText("Registrar medicina");
        btnSchedule.setBorderPainted(false);
        btnSchedule.setContentAreaFilled(false);
        btnSchedule.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSchedulenMouseMoved(evt);
            }
        });
        btnSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnScheduleMouseExited(evt);
            }
        });
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });
        containerBtnSchedule.add(btnSchedule, java.awt.BorderLayout.CENTER);

        jPanel2.add(containerBtnSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 260, 40));

        containerPatient.setBackground(new java.awt.Color(244, 243, 243));
        containerPatient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(244, 243, 243));
        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(35, 36, 37));
        jTextField1.setBorder(null);
        jTextField1.setIgnoreRepaint(true);
        containerPatient.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 30));

        jPanel2.add(containerPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 30));

        jLDate.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLDate.setForeground(new java.awt.Color(35, 36, 37));
        jLDate.setText("Miligramos:");
        jLDate.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        containerDay.setBackground(new java.awt.Color(244, 243, 243));
        containerDay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(244, 243, 243));
        jTextField2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(35, 36, 37));
        jTextField2.setBorder(null);
        jTextField2.setIgnoreRepaint(true);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        containerDay.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 30));

        jPanel2.add(containerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 30));

        jLBeginning.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLBeginning.setForeground(new java.awt.Color(35, 36, 37));
        jLBeginning.setText("Ingrediente activo:");
        jLBeginning.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLBeginning, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        containerEnding.setBackground(new java.awt.Color(244, 243, 243));
        containerEnding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBackground(new java.awt.Color(244, 243, 243));
        jTextField3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(35, 36, 37));
        jTextField3.setBorder(null);
        jTextField3.setIgnoreRepaint(true);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        containerEnding.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 30));

        jPanel2.add(containerEnding, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 260, 30));

        jLDate1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLDate1.setForeground(new java.awt.Color(35, 36, 37));
        jLDate1.setText("Cantidad:");
        jPanel2.add(jLDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 10));

        containerReason.setBackground(new java.awt.Color(244, 243, 243));
        containerReason.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tAReason.setBackground(new java.awt.Color(244, 243, 243));
        tAReason.setColumns(20);
        tAReason.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tAReason.setForeground(new java.awt.Color(35, 36, 37));
        tAReason.setLineWrap(true);
        tAReason.setRows(7);
        tAReason.setTabSize(4);
        tAReason.setIgnoreRepaint(true);
        tAReason.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tAReasonKeyTyped(evt);
            }
        });
        containerReason.add(tAReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 140));

        jPanel2.add(containerReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, 160));

        jLNotes.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLNotes.setForeground(new java.awt.Color(35, 36, 37));
        jLNotes.setText("Indicaciones:");
        jPanel2.add(jLNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 10));

        containerEnding1.setBackground(new java.awt.Color(244, 243, 243));
        containerEnding1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setBackground(new java.awt.Color(244, 243, 243));
        jTextField4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(35, 36, 37));
        jTextField4.setBorder(null);
        jTextField4.setIgnoreRepaint(true);
        containerEnding1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 30));

        jPanel2.add(containerEnding1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 625));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLDay3.setBackground(new java.awt.Color(255, 255, 255));
        jLDay3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLDay3.setForeground(new java.awt.Color(35, 36, 37));
        jLDay3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDay3.setText("Medicamentos");
        jLDay3.setToolTipText("");
        jPanel6.add(jLDay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 580, 30));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 780, 50));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        scrollMedicines.setBackground(new java.awt.Color(255, 255, 255));
        scrollMedicines.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel3.setBackground(new java.awt.Color(244, 243, 243));
        roundedPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 36, 37));
        jLabel1.setText("Nombrej medicamento");
        roundedPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 36, 37));
        jLabel3.setText("Ingrediente activo");
        roundedPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        scrollMedicines.add(roundedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 20, 233, 110));

        roundedPanel4.setBackground(new java.awt.Color(244, 243, 243));
        roundedPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 36, 37));
        jLabel4.setText("Nombrej medicamento");
        roundedPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 20));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(35, 36, 37));
        jLabel5.setText("Ingrediente activo");
        roundedPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 36, 37));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("10 mg");
        roundedPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 80, 60, 20));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(35, 36, 37));
        jLabel10.setText("10 pz");
        roundedPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 60, 20));

        scrollMedicines.add(roundedPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 233, 110));

        roundedPanel5.setBackground(new java.awt.Color(244, 243, 243));
        roundedPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(35, 36, 37));
        jLabel6.setText("Nombrej medicamento");
        roundedPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(35, 36, 37));
        jLabel7.setText("Ingrediente activo");
        roundedPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        scrollMedicines.add(roundedPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 20, 233, 110));

        roundedPanel6.setBackground(new java.awt.Color(244, 243, 243));
        roundedPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 36, 37));
        jLabel8.setText("Nombrej medicamento");
        roundedPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 20));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(35, 36, 37));
        jLabel11.setText("Ingrediente activo");
        roundedPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(35, 36, 37));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("10 mg");
        roundedPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 80, 60, 20));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(35, 36, 37));
        jLabel13.setText("10 pz");
        roundedPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 60, 20));

        scrollMedicines.add(roundedPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 233, 110));

        roundedPanel7.setBackground(new java.awt.Color(244, 243, 243));
        roundedPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(35, 36, 37));
        jLabel14.setText("Nombrej medicamento");
        roundedPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 20));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(35, 36, 37));
        jLabel15.setText("Ingrediente activo");
        roundedPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(35, 36, 37));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("10 mg");
        roundedPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 80, 60, 20));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(35, 36, 37));
        jLabel17.setText("10 pz");
        roundedPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 60, 20));

        scrollMedicines.add(roundedPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 233, 110));

        roundedPanel8.setBackground(new java.awt.Color(244, 243, 243));
        roundedPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(35, 36, 37));
        jLabel18.setText("Nombrej medicamento");
        roundedPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 20));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(35, 36, 37));
        jLabel19.setText("Ingrediente activo");
        roundedPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(35, 36, 37));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("10 mg");
        roundedPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 80, 60, 20));

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(35, 36, 37));
        jLabel21.setText("10 pz");
        roundedPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 60, 20));

        scrollMedicines.add(roundedPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 233, 110));

        jScrollPane1.setViewportView(scrollMedicines);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 780, 575));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSchedulenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSchedulenMouseMoved
        containerBtnSchedule.setBackground(new Color(35, 111, 229));
    }//GEN-LAST:event_btnSchedulenMouseMoved

    private void btnScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScheduleMouseExited
        containerBtnSchedule.setBackground(new Color(37, 119, 241));
    }//GEN-LAST:event_btnScheduleMouseExited

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        if (validateFields()) {
            Medicine md = new Medicine();
            md.setName(jTextField1.getText());
            md.setAmount(Integer.valueOf(jTextField2.getText()));
            md.setIngredient(jTextField4.getText());
            md.setMgIngredient(Integer.valueOf(jTextField3.getText()));
            md.setIndications(tAReason.getText().trim());
            if (MedicineControl.getInstance().addMedicine(md)) {
                App.GetSingleton().newMessage(App.GetSingleton().getMainFrame(), MessageType.CORRECT, "Registrar Medicamento", "Medicamento registrado correctamente");
                renderMedicines();
                cleanFields();
            } else {
                App.GetSingleton().newMessage(App.GetSingleton().getMainFrame(), MessageType.ERROR, "Registrar Medicamento", "Imposible registrar medicamento - Verifique los datos");
            }
        } else {
            App.GetSingleton().newMessage(App.GetSingleton().getMainFrame(), MessageType.ERROR, "Registrar Medicamento", "Imposible registrar medicamento - Campos vacios o incorrectos.");
        }
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void tAReasonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tAReasonKeyTyped
        if (tAReason.getText().length() == 200)
        evt.consume();
    }//GEN-LAST:event_tAReasonKeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c=evt.getKeyChar();
        
	if(Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c=evt.getKeyChar();
        
	if(Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSchedule;
    private Components.RoundedPanel containerBtnSchedule;
    private Components.RoundedPanel containerDay;
    private Components.RoundedPanel containerEnding;
    private Components.RoundedPanel containerEnding1;
    private Components.RoundedPanel containerPatient;
    private Components.RoundedPanel containerReason;
    private javax.swing.JLabel jLBeginning;
    private javax.swing.JLabel jLDate;
    private javax.swing.JLabel jLDate1;
    private javax.swing.JLabel jLDay3;
    private javax.swing.JLabel jLNotes;
    private javax.swing.JLabel jLPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private Components.RoundedPanel roundedPanel3;
    private Components.RoundedPanel roundedPanel4;
    private Components.RoundedPanel roundedPanel5;
    private Components.RoundedPanel roundedPanel6;
    private Components.RoundedPanel roundedPanel7;
    private Components.RoundedPanel roundedPanel8;
    private javax.swing.JPanel scrollMedicines;
    private javax.swing.JTextArea tAReason;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
