/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.PatientDAO;
import Domain.Patient;
import control.PatientControl;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author orlandocamacho
 */
public class scheduleAppointment extends javax.swing.JFrame {

    private int mouseX;
    private int mouseY;
    /**
     * Creates new form home
     */
    public scheduleAppointment() {
        initComponents();
        loadPatients();
        String separator = File.separator;
        
        if (separator.equals("/")) {
            setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 22, 22));
            this.DisposeButtonW.setVisible(false);
            this.MinimizeButtonW.setVisible(false);
            this.FullScreenButtonW.setVisible(false);
        } else {
            setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 0, 0));
            this.DisposeButton.setVisible(false);
            this.MinimizeButton.setVisible(false);
            this.FullScreenButton.setVisible(false);
        }
        setLocationRelativeTo(null); 

    }
    
    private void loadPatients() {
        for (Patient patient : PatientControl.getInstance().getPatients()) {
            cbPatient.addItem(patient);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        DisposeButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        FullScreenButton = new javax.swing.JLabel();
        MinimizeButtonW = new javax.swing.JLabel();
        DisposeButtonW = new javax.swing.JLabel();
        FullScreenButtonW = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lateralMenu = new javax.swing.JPanel();
        roundedPanel1 = new components.RoundedPanel();
        menuScheduleAppointment = new javax.swing.JButton();
        roundedPanel2 = new components.RoundedPanel();
        menuEditAppointment = new javax.swing.JButton();
        roundedPanel3 = new components.RoundedPanel();
        menuDeleteAppointment = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        Patient = new javax.swing.JLabel();
        cbPatient = new javax.swing.JComboBox<>();
        Date = new javax.swing.JLabel();
        cbDate = new javax.swing.JComboBox<>();
        Hour = new javax.swing.JLabel();
        cbHour = new javax.swing.JComboBox<>();
        service = new javax.swing.JLabel();
        cbService = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        AppointmentDescription = new javax.swing.JTextArea();
        scheduleBtn = new components.RoundedPanel();
        scheduleAppointment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(232, 240, 254));
        topBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        topBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarMouseDragged(evt);
            }
        });
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarMousePressed(evt);
            }
        });
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DisposeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DisposeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DisposeButton.png"))); // NOI18N
        DisposeButton.setMaximumSize(new java.awt.Dimension(14, 14));
        DisposeButton.setMinimumSize(new java.awt.Dimension(14, 14));
        DisposeButton.setPreferredSize(new java.awt.Dimension(14, 14));
        DisposeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DisposeButtonMouseMoved(evt);
            }
        });
        DisposeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DisposeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisposeButtonMousePressed(evt);
            }
        });
        topBar.add(DisposeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 35));

        MinimizeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MinimizeButton.png"))); // NOI18N
        MinimizeButton.setMaximumSize(new java.awt.Dimension(14, 14));
        MinimizeButton.setMinimumSize(new java.awt.Dimension(14, 14));
        MinimizeButton.setPreferredSize(new java.awt.Dimension(14, 14));
        MinimizeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseMoved(evt);
            }
        });
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeButtonMousePressed(evt);
            }
        });
        topBar.add(MinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 35));

        FullScreenButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FullScreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FullScreenButton.png"))); // NOI18N
        FullScreenButton.setMaximumSize(new java.awt.Dimension(14, 14));
        FullScreenButton.setMinimumSize(new java.awt.Dimension(14, 14));
        FullScreenButton.setPreferredSize(new java.awt.Dimension(14, 14));
        FullScreenButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FullScreenButtonMouseMoved(evt);
            }
        });
        FullScreenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullScreenButtonMouseExited(evt);
            }
        });
        topBar.add(FullScreenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 35));

        MinimizeButtonW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimizeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MinimizeButtonW.png"))); // NOI18N
        MinimizeButtonW.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MinimizeButtonWMouseMoved(evt);
            }
        });
        MinimizeButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeButtonWMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeButtonWMousePressed(evt);
            }
        });
        topBar.add(MinimizeButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(1103, 2, 55, 33));

        DisposeButtonW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DisposeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DisposeButtonW.png"))); // NOI18N
        DisposeButtonW.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DisposeButtonWMouseMoved(evt);
            }
        });
        DisposeButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DisposeButtonWMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisposeButtonWMousePressed(evt);
            }
        });
        topBar.add(DisposeButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 2, 55, 33));

        FullScreenButtonW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FullScreenButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FullScreenButtonW.png"))); // NOI18N
        FullScreenButtonW.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FullScreenButtonWMouseMoved(evt);
            }
        });
        FullScreenButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullScreenButtonWMouseExited(evt);
            }
        });
        topBar.add(FullScreenButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 2, 55, 33));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 36, 37));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clinica Dra Brenda Cañedo");
        topBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 280, 35));

        getContentPane().add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 35));

        lateralMenu.setBackground(new java.awt.Color(232, 240, 254));
        lateralMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        lateralMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setBackground(new java.awt.Color(204, 204, 204));
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuScheduleAppointment.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        menuScheduleAppointment.setForeground(new java.awt.Color(35, 36, 37));
        menuScheduleAppointment.setText("Agendar cita");
        menuScheduleAppointment.setContentAreaFilled(false);
        menuScheduleAppointment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundedPanel1.add(menuScheduleAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        lateralMenu.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 30));

        roundedPanel2.setBackground(new java.awt.Color(204, 204, 204));
        roundedPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuEditAppointment.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        menuEditAppointment.setForeground(new java.awt.Color(35, 36, 37));
        menuEditAppointment.setText("Editar");
        menuEditAppointment.setContentAreaFilled(false);
        menuEditAppointment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuEditAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditAppointmentActionPerformed(evt);
            }
        });
        roundedPanel2.add(menuEditAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        lateralMenu.add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 30));

        roundedPanel3.setBackground(new java.awt.Color(204, 204, 204));
        roundedPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuDeleteAppointment.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        menuDeleteAppointment.setForeground(new java.awt.Color(35, 36, 37));
        menuDeleteAppointment.setText("Eliminar cita");
        menuDeleteAppointment.setContentAreaFilled(false);
        menuDeleteAppointment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuDeleteAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteAppointmentActionPerformed(evt);
            }
        });
        roundedPanel3.add(menuDeleteAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        lateralMenu.add(roundedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 30));

        getContentPane().add(lateralMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 200, 685));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 36, 37));
        jLabel2.setText("Agendar citas");
        title.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 55));

        content.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        description.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        description.setForeground(new java.awt.Color(35, 36, 37));
        description.setText("Descripción:");
        content.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        Patient.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Patient.setForeground(new java.awt.Color(35, 36, 37));
        Patient.setText("Paciente:");
        content.add(Patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cbPatient.setBackground(new java.awt.Color(204, 204, 204));
        cbPatient.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbPatient.setForeground(new java.awt.Color(35, 36, 37));
        cbPatient.setMaximumRowCount(12);
        cbPatient.setBorder(null);
        cbPatient.setFocusable(false);
        content.add(cbPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 30));

        Date.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(35, 36, 37));
        Date.setText("Fecha:");
        content.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cbDate.setBackground(new java.awt.Color(204, 204, 204));
        cbDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbDate.setForeground(new java.awt.Color(35, 36, 37));
        cbDate.setMaximumRowCount(12);
        cbDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDate.setBorder(null);
        cbDate.setFocusable(false);
        cbDate.setIgnoreRepaint(true);
        cbDate.setLightWeightPopupEnabled(false);
        content.add(cbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 250, 30));

        Hour.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Hour.setForeground(new java.awt.Color(35, 36, 37));
        Hour.setText("Hora:");
        content.add(Hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cbHour.setBackground(new java.awt.Color(204, 204, 204));
        cbHour.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbHour.setForeground(new java.awt.Color(35, 36, 37));
        cbHour.setMaximumRowCount(12);
        cbHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbHour.setBorder(null);
        cbHour.setFocusable(false);
        cbHour.setIgnoreRepaint(true);
        cbHour.setLightWeightPopupEnabled(false);
        content.add(cbHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 30));

        service.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        service.setForeground(new java.awt.Color(35, 36, 37));
        service.setText("Servicio:");
        content.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        cbService.setBackground(new java.awt.Color(204, 204, 204));
        cbService.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbService.setForeground(new java.awt.Color(35, 36, 37));
        cbService.setMaximumRowCount(12);
        cbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbService.setBorder(null);
        cbService.setFocusable(false);
        cbService.setIgnoreRepaint(true);
        cbService.setLightWeightPopupEnabled(false);
        content.add(cbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 250, 30));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        AppointmentDescription.setBackground(new java.awt.Color(255, 255, 255));
        AppointmentDescription.setColumns(19);
        AppointmentDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        AppointmentDescription.setForeground(new java.awt.Color(35, 36, 37));
        AppointmentDescription.setRows(5);
        jScrollPane1.setViewportView(AppointmentDescription);

        content.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 250, 140));

        scheduleBtn.setBackground(new java.awt.Color(0, 102, 255));
        scheduleBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scheduleAppointment.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        scheduleAppointment.setForeground(new java.awt.Color(255, 255, 255));
        scheduleAppointment.setText("Agendar cita");
        scheduleAppointment.setContentAreaFilled(false);
        scheduleBtn.add(scheduleAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        content.add(scheduleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 250, 40));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 35, 1080, 685));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisposeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonMouseMoved
        DisposeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DisposeButton2.png")));
    }//GEN-LAST:event_DisposeButtonMouseMoved

    private void DisposeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonMouseExited
        DisposeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DisposeButton.png")));
    }//GEN-LAST:event_DisposeButtonMouseExited

    private void DisposeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonMousePressed
        if (evt.getClickCount() >= 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_DisposeButtonMousePressed

    private void MinimizeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseMoved
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MinimizeButton2.png")));
    }//GEN-LAST:event_MinimizeButtonMouseMoved

    private void MinimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseExited
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MinimizeButton.png")));
    }//GEN-LAST:event_MinimizeButtonMouseExited

    private void MinimizeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMousePressed
        if (evt.getClickCount() >= 0) {
            this.setExtendedState(1);
        }
    }//GEN-LAST:event_MinimizeButtonMousePressed

    private void FullScreenButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonMouseMoved
        FullScreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FullScreenButton2.png")));
    }//GEN-LAST:event_FullScreenButtonMouseMoved

    private void FullScreenButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonMouseExited
        FullScreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FullScreenButton.png")));
    }//GEN-LAST:event_FullScreenButtonMouseExited

    private void MinimizeButtonWMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonWMouseMoved
        MinimizeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MinimizeButtonW2.png")));
    }//GEN-LAST:event_MinimizeButtonWMouseMoved

    private void MinimizeButtonWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonWMouseExited
        MinimizeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MinimizeButtonW.png")));
    }//GEN-LAST:event_MinimizeButtonWMouseExited

    private void MinimizeButtonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonWMousePressed
        if (evt.getClickCount() >= 0) {
            this.setExtendedState(1);
        }
    }//GEN-LAST:event_MinimizeButtonWMousePressed

    private void DisposeButtonWMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonWMouseMoved
        DisposeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DisposeButtonW2.png")));
    }//GEN-LAST:event_DisposeButtonWMouseMoved

    private void DisposeButtonWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonWMouseExited
        DisposeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DisposeButtonW.png")));
    }//GEN-LAST:event_DisposeButtonWMouseExited

    private void DisposeButtonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonWMousePressed
        if (evt.getClickCount() >= 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_DisposeButtonWMousePressed

    private void FullScreenButtonWMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonWMouseMoved
        FullScreenButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FullScreenButtonW2.png")));
    }//GEN-LAST:event_FullScreenButtonWMouseMoved

    private void FullScreenButtonWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonWMouseExited
        FullScreenButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FullScreenButtonW.png")));
    }//GEN-LAST:event_FullScreenButtonWMouseExited

    private void topBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_topBarMousePressed

    private void topBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        setLocation(X - mouseX, Y - mouseY + 1);
    }//GEN-LAST:event_topBarMouseDragged

    private void menuEditAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditAppointmentActionPerformed
        editAppointment edit = new editAppointment();
        edit.setVisible(true);
        this.setVisible(false);
        System.gc();
    }//GEN-LAST:event_menuEditAppointmentActionPerformed

    private void menuDeleteAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteAppointmentActionPerformed
        deleteAppointment delete = new deleteAppointment();
        delete.setVisible(true);
        this.setVisible(false);
        System.gc();
    }//GEN-LAST:event_menuDeleteAppointmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scheduleAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scheduleAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scheduleAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheduleAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheduleAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AppointmentDescription;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DisposeButton;
    private javax.swing.JLabel DisposeButtonW;
    private javax.swing.JLabel FullScreenButton;
    private javax.swing.JLabel FullScreenButtonW;
    private javax.swing.JLabel Hour;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JLabel MinimizeButtonW;
    private javax.swing.JLabel Patient;
    private javax.swing.JComboBox<String> cbDate;
    private javax.swing.JComboBox<String> cbHour;
    private javax.swing.JComboBox<Patient> cbPatient;
    private javax.swing.JComboBox<String> cbService;
    private javax.swing.JPanel content;
    private javax.swing.JLabel description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lateralMenu;
    private javax.swing.JButton menuDeleteAppointment;
    private javax.swing.JButton menuEditAppointment;
    private javax.swing.JButton menuScheduleAppointment;
    private components.RoundedPanel roundedPanel1;
    private components.RoundedPanel roundedPanel2;
    private components.RoundedPanel roundedPanel3;
    private javax.swing.JButton scheduleAppointment;
    private components.RoundedPanel scheduleBtn;
    private javax.swing.JLabel service;
    private javax.swing.JPanel title;
    private javax.swing.JPanel topBar;
    // End of variables declaration//GEN-END:variables
}
